### PR TITLE
Janvier

### PR DESCRIPTION
**Pull request by mugijanvier**
@alptilev  the high_Chart PV_production and Cloud Cover

### CODE REVIEW

**Comment by mugijanvier** [comment]
I Wait for the feedback

**Comment by jlark** [comment]
Please remove all .idea files and Libraries from the commit. Only the files you've modified should be pushed in to the repo.

Please modify the .gitignore to ignore the .idea folder. Info on how to ignore directories can be found here
http://stackoverflow.com/questions/1470572/gitignore-ignore-any-bin-directory

**Comment by mugijanvier** [comment]
ok. let me do it

2015-12-03 17:19 GMT+02:00 Alp Tilev <notifications@github.com>:

**Comment by jlark** [comment]
Please remove files that are autogenerate,libraries,IDE related etc. Only commit files you modified.

Move any libraries to bower config in settings.py  or requirements.txt

**Comment by mugijanvier** [comment]
thanks. let me do it tomorrow. have a nice evening.

2015-12-03 17:55 GMT+02:00 janvier mugisha <mugijanvier@gmail.com>:

**Comment by mugijanvier** [comment]
i close the pull request. i will try to give u the best one.
but i am not getting well the ignore !!
loll

2015-12-03 17:58 GMT+02:00 janvier mugisha <mugijanvier@gmail.com>:

**Pull request closed without merging**
