### PR TITLE
WORK IN  PROGRESS: New dashboardd

### PR DESCRIPTION
**Pull request by upatricck**
The new dashboard

## CHagnes
* Working on the new layout

Also removed some big files that has been accidentally added therefore modifying the git intire history

### CODE REVIEW

**Comment by jlark** [comment]
Can i see some screenshots?

**Comment by rawjazz** [comment]
screenshot from 2016-06-15 04 37 03

**Comment by rawjazz** [comment]
wp!

**Comment by jlark** [comment]
Ok can you change the title of the PR and add [WIP]  just so i know this is a work in progress.

**Comment by upatricck** [comment]
The work has seemed to be long, we found out that we have to also edit some of the views to minimize the number of uneccessary post request

**Comment by upatricck** [comment]
Also it looks like we have to remove the old tests

**Comment by Frankkwizera** [comment]
sesh1
sesh4

**Comment by alptilev** [comment]
Does the template have its table layout for the form ls that mught be sexier?

Mobile typing




On Thu, Jun 16, 2016 at 1:38 PM +0300, "Frank" <notifications@github.com> wrote:





sesh1
sesh4


---

**Comment by jlark** [comment]
Status here?

**Comment by rawjazz** [comment]
screenshot from 2016-06-27 11 17 47

**Comment by jlark** [comment]
looking nice!

**Pull request merged**
