### PR TITLE
Setting up for a new Dashboard

### PR DESCRIPTION
**Pull request by rawjazz**
Setting up for the new look of the Dashboard

### CODE REVIEW

**Comment by jlark** [comment]
@rawjazz I'm assuming this is a Work In Progress PR?

**Comment by rawjazz** [comment]
yeah it is a WP

**Comment by rawjazz** [comment]
starting with login screen
screenshot from 2016-06-09 16 51 42

**Comment by jlark** [comment]
Nice 'Dash Board' shpuld be one word. Also can you grab the logo of gle from Rachel?

**Comment by Frankkwizera** [comment]
starting on it tomorrow

**Pull request closed without merging**
