### PR TITLE
User configurations

### PR DESCRIPTION
**Pull request by Frankkwizera**
setting user permissions
#still on it.

### CODE REVIEW

**Comment by Frankkwizera** [comment]
pic

**Comment by Frankkwizera** [comment]
those parts are hidden.
but still configuring to denie  urls

**Comment by Frankkwizera** [comment]
i mean deny!!

**Comment by jlark** [comment]
Can you show me how it looks for a super user?

**Comment by Frankkwizera** [comment]
admin
here the admin

**Pull request merged**
