### PR TITLE
added ability to add, edit and delete alert_rules in the settings menu

### PR DESCRIPTION
**Pull request by upatricck**
Working on the sesh settings

Done
* Added the ability to add, edit and delete alert rules in the settings.

Closing issue #321

### CODE REVIEW

**Comment by upatricck** [comment]
Closing issue #321, #329  and #327

**Comment by jlark** [comment]
Can you add a screenshot?

**Comment by upatricck** [comment]
Yeah, will do.

**Comment by upatricck** [comment]
Screeshots... 
screenshot from 2016-08-26 13 35 58
screenshot from 2016-08-26 13 33 33

**Comment by upatricck** [comment]
screenshot from 2016-08-26 13 43 19

**Pull request merged**
