### PR TITLE
Fixing issues

### PR DESCRIPTION
**Pull request by upatricck**
Fixed issue in styling of the add report ui,

Fixing issue #390 

screenshot from 2017-02-23 12 05 13

### CODE REVIEW

**Comment by jlark** [comment]
Can you look at the TODO in #420 and push this to the same PR?

**Comment by jlark** [comment]
any news here?

**Comment by upatricck** [comment]
Working on it, i will send the updates here.

**Comment by jlark** [comment]
Is this finished?

**Comment by upatricck** [comment]
Yes it is finished

**Comment by jlark** [comment]
Which issues are handled in this PR?

**Comment by jlark** [comment]
#428 ?

**Comment by jlark** [comment]
LGTM

**Pull request merged**
